spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/advanced_sql_main_task_db
    password: Way_0804
    username: postgres
  jpa:
    generate-ddl: false
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: validate